INSERT INTO REVIEWER (ID,DISPLAY_NAME,CITY,STATE,ZIPCODE, DAIRY_ALLERGY, EGG_ALLERGY, PEANUT_ALLERGY) VALUES (1001, 'Bob Smith', 'Oakville', 'Ontario', 'L6H2P3', true, false, false);
INSERT INTO REVIEWER (ID,DISPLAY_NAME,CITY,STATE,ZIPCODE, DAIRY_ALLERGY, EGG_ALLERGY, PEANUT_ALLERGY) VALUES (1002, 'Kanchana Patel', 'Oakville', 'Ontario', 'L7H2P4', false, true, false);
INSERT INTO REVIEWER (ID,DISPLAY_NAME,CITY,STATE,ZIPCODE, DAIRY_ALLERGY, EGG_ALLERGY, PEANUT_ALLERGY) VALUES (1003, 'Able Lee', 'Ottawa', 'Ontario', 'Q3F4D4', true, true, true);
INSERT INTO RESTAURANT (ID,NAME, CITY, STATE, ZIPCODE, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE) VALUES (10001, 'MacScoops', 'Toronto', 'Ontario', 'M5P1P9', 2.3, 4, 5);
INSERT INTO RESTAURANT (ID,NAME, CITY, STATE, ZIPCODE, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE) VALUES (10002, 'MacScoops', 'Toronto', 'Ontario', 'M2Q1P9', 1, 1, 1);
INSERT INTO RESTAURANT (ID,NAME, CITY, STATE, ZIPCODE, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE) VALUES (10005, 'Fancy Feets', 'Toronto', 'Ontario', 'M3P1G9', 2, 1.5, 0);
INSERT INTO RESTAURANT (ID,NAME, CITY, STATE, ZIPCODE, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE) VALUES (10006, 'Elysium', 'Toronto', 'Ontario', 'M8W3F6', 0, 0, 0);
INSERT INTO DINING_REVIEW (ID,RESTAURANT_ID, COMMENTARY, SUBMITTED_BY, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE, REVIEW_STATUS) VALUES (100001, 10002, 'I was attacked by bees while eating here. Bring an epi-pen.', 'Able Lee', 1, 1, 1, 0);
INSERT INTO DINING_REVIEW (ID,RESTAURANT_ID, COMMENTARY, SUBMITTED_BY, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE, REVIEW_STATUS) VALUES (100002, 10002, 'Best fries ever, too bad about the bees', 'Bob Smith', 5, 5, 2, 1);
INSERT INTO DINING_REVIEW (ID,RESTAURANT_ID, COMMENTARY, SUBMITTED_BY, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE, REVIEW_STATUS) VALUES (100003, 10002, 'Buy bitcoin now, link in bio!', 'Kanchana Patel', 3, 2, 5, 2);
INSERT INTO DINING_REVIEW (ID,RESTAURANT_ID, COMMENTARY, SUBMITTED_BY, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE, REVIEW_STATUS) VALUES (100004, 10005, 'Too expensive, no parking!', 'Able Lee', 3, 1, 1, 0);
INSERT INTO DINING_REVIEW (ID,RESTAURANT_ID, COMMENTARY, SUBMITTED_BY, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE, REVIEW_STATUS) VALUES (100005, 10002, 'GArbledenia!', 'Able Lee', 1, 1, 1, 0);
INSERT INTO DINING_REVIEW (ID,RESTAURANT_ID, COMMENTARY, SUBMITTED_BY, DAIRY_SCORE, EGG_SCORE, PEANUT_SCORE, REVIEW_STATUS) VALUES (100006, 10006, 'Best carpacio in town, very few bees', 'Kanchana Patel', 1, 1, 1, 0);

